### ISSUE TITLE
keyword spotting won't run

### ISSUE THREAD

**Issue by trappedinspacetime** [chmp/misc-exp#19]
Hi,
I read your post [here](https://cprohm.de/article/keyword-detection-from-scratch.html/)
I tried to test it after installing `  pip install ./chmp-app-kwdetect` 
then 
      python -m chmp.app.kwdetect detect --model ./run/model/model.pickle ./data
but I get the following error:

       ModuleNotFoundError: No module named 'chmp.label'
I am on Ubuntu 22.04 
      python --version 
      Python 3.10.7

**Comment by chmp** [comment]
TBH. This code fell a bit into disrepair. Try installing the support package `chmp` directly from this repo:

```
pip install ./chmp
pip install ./chmp-app-kwdetect
````

Maybe you also need to checkout an old commit.

**Comment by trappedinspacetime** [comment]
@chmp Thank you for responding. I did what you suggest, I don't get that error but 
when I run 

        python -m chmp.app.kwdetect label ./data
after 

        python -m chmp.app.kwdetect detect ./data
        
I get :

         Traceback (most recent call last):
    File "/home/****/.pyenv/versions/3.10.7/lib/python3.10/runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/home/****/.pyenv/versions/3.10.7/lib/python3.10/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/home/****/.pyenv/versions/3.10.7/lib/python3.10/site-packages/chmp/app/kwdetect/__main__.py", line 124, in <module>
      main()
    File "/home/****/.pyenv/versions/3.10.7/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
      return self.main(*args, **kwargs)
    File "/home/****/.pyenv/versions/3.10.7/lib/python3.10/site-packages/click/core.py", line 1055, in main
      rv = self.invoke(ctx)
    File "/home/****/.pyenv/versions/3.10.7/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/home/****/.pyenv/versions/3.10.7/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/home/****/.pyenv/versions/3.10.7/lib/python3.10/site-packages/click/core.py", line 760, in invoke
      return __callback(*args, **kwargs)
    File "/home/****/.pyenv/versions/3.10.7/lib/python3.10/site-packages/chmp/app/kwdetect/__main__.py", line 49, in label
      with open(labels, 'rt') as fobj:
  TypeError: expected str, bytes or os.PathLike object, not NoneType
